apiVersion: v1
kind: Service
metadata:
  labels:
    app: allcomhub
  name: demoapp-svc
  namespace: allcomhub-ns
spec:
  ports:
  - name: allcomhub-ports
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 8001
  selector:
    app: allcomhub
  type: NodePort
